### PR TITLE
Recursively include dependencies

### PR DESCRIPTION
**Pull request by lennym**
This means that dependencies of dependencies can still be loaded out of their parents' ./node_modules directory.

General resolution strategy:

1. Look for a candidate local/relative file by constructing a glob - if it exists, import that
2. Get the module name as anything before the first `/` in the import path - attempt to resolve this to an installed node module by doing findup of ./node_modules directories.
3. If an installed module is found, look for the defined path within the module directory if it is defined.
4. Else look for a `styles` declaration in package.json
5. Else look for `./styles` in module root
6. If no matching module is found, revert to standard sass import path and let sass fail if it cannot resolve

### CODE REVIEW

**Comment by lennym** [comment]
@gavboulton - I know Passports are using this module pretty heavily, so I'd been keen to know if the major version update that contains this code (1.0.0) works against your codebase or not as it's a massive PITA to test various potentially complex dependency trees.

If you were able to bump to v1.0.0 for some of the passports projects and let me know if it breaks anything then that would be super awesome.

**Comment by gavboulton** [comment]
Hey @lennym. I can certainly test this but it won't be until next year unfortunately.

**Comment by lennym** [comment]
@gavboulton 

Yeah, that's no problem at all. I'm off work myself as soon as I've finished typing this message.

Merry Christmas!

**Comment by anarh** [comment]
Hey @lennym, @mikemaccana et.al, I just now noticed your work here and [sass-npm](https://github.com/mikemaccana/sass-npm) by Mike right after I pushed mine up You may want to consider using [npm resolve](https://www.npmjs.com/package/resolve) to handle all resolutions so users who change their default node_modules directory can still find modules. You currently have 'node_modules' hard-coded with your lookup. 

Anyway, here's mine, [node-sass-import](https://github.com/anarh/node-sass-import)

**Comment by lennym** [comment]
Hey @anarh 

Thanks for your input. I really like what you've done with `resolve` as it basically removes all the hack I put in to try to import modules relative to the importing file.

**Comment by anarh** [comment]
Hey @lennym 
Thanks, perhaps at some point we can take the best from each repo and consider merging under one umbrella.

**Pull request merged**
